# Generated by Django 4.0.5 on 2022-08-09 23:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweeter', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twit',
            name='users_like',
        ),
        migrations.AddField(
            model_name='twit',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_twits', to=settings.AUTH_USER_MODEL),
        ),
    ]
